### ISSUE TITLE
Sharing the KML :)

### ISSUE THREAD

**Issue by PhantomDeep** [PCigales/Kml_from_photos#2]
Hi,

It's me again! I've gotten all the renders to work properly on my home PC. I was trying to share it via OneDrive, but it didn't seem to render the thumbs when the same file was clicked. I even downloaded the entire "Test" folder, which contacted the thumbs file, onto the local computer. Would each computer require the software noted in your GitHub? I was merely trying to sync the KML onto google earth via chrome and VML upload.

**Comment by PCigales** [comment]
Hi,

it is possible to load the generated kml file in Google Earth Pro on another computer, provided that:
\- the kml file, the "thumbs" directory, and the "viewer.htm" file are copied in a same folder
\- the absolute path to this folder is exactly the same as what it was on the computer where the batch was run
If the second condition is not fulfilled, then the kml file has to be edited, and each occurrence of the former path to the folder must be replaced with the new one. I remember that I tried to use relative pathes, but it gave incoherent results.

Besides, to be able to display the original pictures from the balloons of the placemarks, the path to these files must also be the same.

**Comment by PhantomDeep** [comment]
I have the KML file created by the kml.bat, the "thumbs" directory and viewer. 
The absolute path is affected by the PC naming though. From "Justin" to "XXXXXXX" work PC. 
Very helpful though, the render works correctly by changing the PC name in the KML. Posses for a new complication of sharing it to any PC and some with less technical skills than mine haha.

**Comment by PCigales** [comment]
If you intend to share the kml file and its dependencies, the kmz format is more suited: it will fit your needs better because it can embed the images and rmake use of relative links.
A kmz file can be generated from Google Earth or by adapting the batch. There would be several questions to answer: are the full sized photos to be shared and integrated to the kmz file (its size may become very large) ? what version of Windows runs the computer used for executing the batch, as it affects the way the kmz content can be zipped ?

**Comment by PhantomDeep** [comment]
I don't think the full size images need to be imbedded, just the batch photos with links to one drive.

My computer is using windows 11 pro.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by PCigales** [comment]
I have added a new batch, kmz.bat. It will generate a kmz file embedding the thumbnails.
As for the links to one drive you mention, I have no idea what they look like and how they can be deduced from the path to the full sized photos.

**Comment by PhantomDeep** [comment]
Awesome. I'll hopefully be able to figure that out! Very awesome code you generated.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
